eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.my-eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/
  
---
spring:
  profiles: cloud
eureka:
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
